feat: configurable rotation and flip parameters

diff --git a/.github/workflows/integration_delivery.yml b/.github/workflows/integration_delivery.yml
--- a/.github/workflows/integration_delivery.yml
+++ b/.github/workflows/integration_delivery.yml
@@ -16,14 +16,14 @@ jobs:
       - uses: actions/checkout@v4
         name: Checkout
 
-      - name: Save Cached Poetry
+      - name: Load Cached Poetry
         id: cached-poetry
         uses: actions/cache@v4
         with:
           path: |
             ~/.cache
             ~/.local
-          key: poetry-${{ hashFiles('poetry.lock') }}
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
 
       - uses: actions/setup-python@v5
         name: Setup Python
@@ -61,7 +61,7 @@ jobs:
           path: |
             ~/.cache
             ~/.local
-          key: poetry-${{ hashFiles('poetry.lock') }}
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
 
       - name: Create stub files
         run: poetry run pyright --createstub kivy
@@ -78,8 +78,8 @@ jobs:
       - uses: actions/checkout@v4
         name: Checkout
 
-      - uses: actions/setup-python@v5
-        name: Setup Python
+      - name: Setup Python
+        uses: actions/setup-python@v5
         with:
           python-version: ${{ env.PYTHON_VERSION }}
           architecture: x64
@@ -91,7 +91,7 @@ jobs:
           path: |
             ~/.cache
             ~/.local
-          key: poetry-${{ hashFiles('poetry.lock') }}
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
 
       - name: Lint
         run: poetry run poe lint
@@ -102,8 +102,8 @@ jobs:
       - dependencies
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.extract_version.outputs.version }}
-      name: ${{ steps.extract_version.outputs.name }}
+      version: ${{ steps.extract-version.outputs.VERSION }}
+      name: ${{ steps.extract-version.outputs.NAME }}
     steps:
       - uses: actions/checkout@v4
         name: Checkout
@@ -121,16 +121,41 @@ jobs:
           path: |
             ~/.cache
             ~/.local
-          key: poetry-${{ hashFiles('poetry.lock') }}
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
+
+      - name: Extract Version
+        id: extract-version
+        run: |
+          echo "VERSION=$(poetry version --short)" >> "$GITHUB_OUTPUT"
+          echo "VERSION=$(poetry version --short)"
+          echo "NAME=$(poetry version | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"
+          echo "NAME=$(poetry version | cut -d' ' -f1)"
+
+      - name: Extract Version from CHANGELOG.md
+        run: |
+          VERSION_CHANGELOG=$(sed -n '3 s/## Version //p' CHANGELOG.md) 
+          echo "VERSION_CHANGELOG=$VERSION_CHANGELOG"
+          if [ "${{ steps.extract-version.outputs.VERSION }}" != "$VERSION_CHANGELOG" ]; then
+            echo "Error: Version extracted from CHANGELOG.md does not match the version in pyproject.toml"
+            exit 1 
+          else
+            echo "Versions are consistent."
+          fi
+
+      - name: Extract Version from Tag
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          VERSION_TAG=$(sed 's/^v//' <<< ${{ github.ref_name }})
+          echo "VERSION_TAG=$VERSION_TAG"
+          if [ "${{ steps.extract-version.outputs.VERSION }}" != "$VERSION_TAG" ]; then
+            echo "Error: Version extracted from tag does not match the version in pyproject.toml"
+            exit 1 
+          else
+            echo "Versions are consistent."
+          fi
 
       - name: Build
         run: poetry build
-
-      - name: Extract Version
-        id: extract_version
-        run: |
-          echo "version=$(poetry version --short)" >> "$GITHUB_OUTPUT"
-          echo "name=$(poetry version | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"
 
       - name: Upload wheel
         uses: actions/upload-artifact@v4
@@ -156,7 +181,7 @@ jobs:
       - build
     runs-on: ubuntu-latest
     environment:
-      name: release
+      name: pypi
       url: https://pypi.org/p/${{ needs.build.outputs.name }}
     permissions:
       id-token: write
@@ -178,19 +203,21 @@ jobs:
           verbose: true
 
   release:
+    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
     name: Release
     needs:
       - type-check
       - lint
       - build
       - pypi-publish
+    runs-on: ubuntu-latest
     environment:
       name: release
-      url: https://pypi.org/p/${{ needs.build.outputs.name }}
-    runs-on: ubuntu-latest
+      url:
+        https://github.com/${{ github.repository }}/releases/tag/v${{
+        needs.build.outputs.version }}
     permissions:
       contents: write
-    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
     steps:
       - name: Procure Wheel
         uses: actions/download-artifact@v4
@@ -204,13 +231,28 @@ jobs:
           name: binary
           path: artifacts
 
+      - uses: actions/checkout@v4
+        name: Checkout
+
+      - name: Extract Changelog
+        id: changelog
+        run: |
+          perl -0777 -ne 'while (/## Version ${{ needs.build.outputs.version }}\n(\s*\n)*(.*?)(\s*\n)*## Version \d+\.\d+\.\d+\n/sg) {print "$2\n"}' CHANGELOG.md > CURRENT_CHANGELOG.md
+          {
+            echo "CONTENT<<EOF"
+            cat CURRENT_CHANGELOG.md
+            echo "EOF"
+          } >> "$GITHUB_OUTPUT"
+
       - name: Release
         uses: softprops/action-gh-release@v2
         with:
           files: artifacts/*
           tag_name: v${{ needs.build.outputs.version }}
           body: |
-            Release of version ${{ needs.build.outputs.version }}
             PyPI package: https://pypi.org/project/${{ needs.build.outputs.name }}/${{ needs.build.outputs.version }}
+
+            # Changes:
+            ${{ steps.changelog.outputs.CONTENT }}
           prerelease: false
           draft: false
